### ISSUE TITLE
data-connector-agent: Boot notification message not received due to OTLP connection refused (port 4317)

### ISSUE THREAD

**Issue by mohammdkhalilii** [citrineos/citrineos#129]
**Which repository?**
- citrineos-core

**Describe the bug**
The `data-connector-agent` container fails to export spans due to a connection refusal error (`localhost/127.0.0.1:4317`). As a result, the boot notification message is not received, even though all Docker containers in the project are running and healthy.

Error from the logs:
```
2025-04-16 10:34:44 {"timestamp":"2025-04-16T07:04:44.614892461Z","sequence":118,"loggerClassName":"org.jboss.logmanager.Logger","loggerName":"io.quarkus.opentelemetry.runtime.exporter.otlp.VertxGrpcExporter","level":"SEVERE","message":"Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317","threadName":"vert.x-eventloop-thread-2","threadId":28,"mdc":{},"ndc":"","hostName":"4e9ce9ed1802","processName":"super-connector.jar","processId":1}
```

**To Reproduce**
1. Clone and set up the citrineos-core project (version 1.6.1 main).
2. Follow the project's provided Docker-compose setup instructions.
3. Start all Docker containers.
4. Check the logs of the `data-connector-agent` container.
5. See the reported connection refused error.

**Expected behavior**
The spans should be exported successfully without connection errors, and the boot notification message should be received correctly.

**Screenshots**
<img width="1467" alt="Image" src="https://github.com/user-attachments/assets/594322cd-c9c9-48a5-a143-96ce5517fc98" />

**Desktop (please complete the following information):**
- OS: macOS, Ubuntu 22, Arch Linux
- Browser: Not Applicable
- Version: Latest (1.6.1 main)

**Smartphone (please complete the following information):**
- Not Applicable

**Additional context**
No service/container appears to be listening on port 4317. Clarification on whether this port should have an active listener is required.

**Comment by mohammdkhalilii** [comment]
### ✅ Solution to Docker Compose Issues on Linux/Mac for CitrineOS + Directus + Hasura

We encountered issues running the `docker-compose-directus.yml` file provided in CitrineOS v1.6.2 on **Linux and macOS**, particularly:

---

#### ❌ Problems

1. `host.docker.internal` is **not resolvable on Linux**, causing Hasura to fail PostgreSQL connection:
   ```
   could not translate host name "host.docker.internal" to address: Name or service not known
   ```

2. `data-connector-agent` logs were flooded with:
   ```
   Failed to export spans. Connection refused: localhost/127.0.0.1:4317
   ```
   This was caused by OpenTelemetry exporting attempts, even though we did not enable tracing.

3. Services like Hasura and Directus were **starting before Postgres was ready**, causing race conditions and connection errors.

---

### ✅ Fixes Applied

We resolved the issues by:

#### 🔁 1. Replacing `host.docker.internal` with `ocpp-db`
Since all services are on the same Docker network, we switched to using the container name (`ocpp-db`) in the `HASURA_GRAPHQL_DATABASE_URL` and Directus DB settings.

#### 🔇 2. Disabling OpenTelemetry export in `data-connector-agent`
We disabled the SDK by adding the following environment variable:
```yaml
QUARKUS_OTEL_SDK_DISABLED: 'true'
```

This prevents unnecessary connection attempts to `localhost:4317` (OTLP endpoint), cleaning up the logs.

#### ⏱️ 3. Adding health checks and proper `depends_on` usage
We added `healthcheck` to `ocpp-db` and other services, and made Hasura, Directus, and CitrineOS wait for them to become healthy before starting, using:
```yaml
depends_on:
  ocpp-db:
    condition: service_healthy
```

---

### 📦 Full Working `docker-compose-directus.yml`

A fully working version of the file is attached [in the comment/file above] with all the changes.
Correct docker-compose-directus.yml is:
```
version: '3.8'

services:
  amqp-broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  ocpp-db:
    image: postgis/postgis:16-3.5
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: citrine
      POSTGRES_USER: citrine
      POSTGRES_PASSWORD: 'citrine'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citrine -d citrine"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  citrine:
    build:
      context: ../
      dockerfile: ./Server/deploy.Dockerfile
    volumes:
      - ../package-lock.json:/usr/local/apps/citrineos/package-lock-host.json
      - ../package.json:/usr/local/apps/citrineos/package.json
      - ../tsconfig.json:/usr/local/apps/citrineos/tsconfig.json
      - ../tsconfig.build.json:/usr/local/apps/citrineos/tsconfig.build.json
      - ../Server:/usr/local/apps/citrineos/Server
      - ../00_Base:/usr/local/apps/citrineos/00_Base
      - ../01_Data:/usr/local/apps/citrineos/01_Data
      - ../02_Util:/usr/local/apps/citrineos/02_Util
      - ../03_Modules/Certificates:/usr/local/apps/citrineos/03_Modules/Certificates
      - ../03_Modules/Configuration:/usr/local/apps/citrineos/03_Modules/Configuration
      - ../03_Modules/EVDriver:/usr/local/apps/citrineos/03_Modules/EVDriver
      - ../03_Modules/Monitoring:/usr/local/apps/citrineos/03_Modules/Monitoring
      - ../03_Modules/OcppRouter:/usr/local/apps/citrineos/03_Modules/OcppRouter
      - ../03_Modules/Reporting:/usr/local/apps/citrineos/03_Modules/Reporting
      - ../03_Modules/SmartCharging:/usr/local/apps/citrineos/03_Modules/SmartCharging
      - ../03_Modules/Transactions:/usr/local/apps/citrineos/03_Modules/Transactions
      - /usr/local/apps/citrineos/node_modules
      - /usr/local/apps/citrineos/Server/node_modules
      - /usr/local/apps/citrineos/00_Base/node_modules
      - /usr/local/apps/citrineos/01_Data/node_modules
      - /usr/local/apps/citrineos/02_Util/node_modules
      - /usr/local/apps/citrineos/03_Modules/Certificates/node_modules
      - /usr/local/apps/citrineos/03_Modules/Configuration/node_modules
      - /usr/local/apps/citrineos/03_Modules/EVDriver/node_modules
      - /usr/local/apps/citrineos/03_Modules/Monitoring/node_modules
      - /usr/local/apps/citrineos/03_Modules/OcppRouter/node_modules
      - /usr/local/apps/citrineos/03_Modules/Reporting/node_modules
      - /usr/local/apps/citrineos/03_Modules/SmartCharging/node_modules
      - /usr/local/apps/citrineos/03_Modules/Transactions/node_modules
      - /usr/local/apps/citrineos/dist/
      - /usr/local/apps/citrineos/Server/dist/
      - /usr/local/apps/citrineos/00_Base/dist/
      - /usr/local/apps/citrineos/01_Data/dist/
      - /usr/local/apps/citrineos/02_Util/dist/
      - /usr/local/apps/citrineos/03_Modules/Certificates/dist/
      - /usr/local/apps/citrineos/03_Modules/Configuration/dist/
      - /usr/local/apps/citrineos/03_Modules/EVDriver/dist/
      - /usr/local/apps/citrineos/03_Modules/Monitoring/dist/
      - /usr/local/apps/citrineos/03_Modules/OcppRouter/dist/
      - /usr/local/apps/citrineos/03_Modules/Reporting/dist/
      - /usr/local/apps/citrineos/03_Modules/SmartCharging/dist/
      - /usr/local/apps/citrineos/03_Modules/Transactions/dist/
    environment:
      APP_NAME: 'all'
      APP_ENV: 'directus'
      AWS_REGION: us-east-1
      CITRINEOS_UTIL_FILEACCESS_DIRECTUS_TOKEN: 'MY_DIRECTUS_STATIC_TOKEN'
    depends_on:
      ocpp-db:
        condition: service_healthy
      amqp-broker:
        condition: service_healthy
      directus:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8085:8085
      - 8443:8443
      - 8444:8444
      - 9229:9229
      - 8092:8092

  directus:
    build:
      context: ../DirectusExtensions
      dockerfile: ./directus.Dockerfile
    ports:
      - 8055:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./directus-env-config.cjs:/directus/config.cjs
    depends_on:
      ocpp-db:
        condition: service_healthy
    environment:
      APP_NAME: 'all'
      KEY: '1234567890'
      SECRET: '0987654321'
      ADMIN_EMAIL: 'admin@citrineos.com'
      ADMIN_PASSWORD: 'CitrineOS!'
      CONFIG_PATH: '/directus/config.cjs'
      EXTENSIONS_AUTO_RELOAD: 'true'
      EXTENSIONS_CACHE_TTL: '1s'
      DB_CLIENT: 'pg'
      DB_HOST: ocpp-db
      DB_PORT: 5432
      DB_DATABASE: 'citrine'
      DB_USER: 'citrine'
      DB_PASSWORD: 'citrine'
      WEBSOCKETS_ENABLED: 'true'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8055/server/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3

  graphql-engine:
    image: hasura/graphql-engine:v2.40.3.cli-migrations-v3
    volumes:
      - ./hasura-metadata:/hasura-metadata
    ports:
      - 8090:8080
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://citrine:citrine@ocpp-db:5432/citrine
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
    depends_on:
      data-connector-agent:
        condition: service_healthy
      ocpp-db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/healthz']
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s

  data-connector-agent:
    image: hasura/graphql-data-connector:v2.40.3
    restart: always
    ports:
      - 8091:8081
    environment:
      QUARKUS_LOG_LEVEL: ERROR
      QUARKUS_OPENTELEMETRY_ENABLED: 'false'
      QUARKUS_OTEL_SDK_DISABLED: 'true'
    depends_on:
      ocpp-db:
        condition: service_healthy
      amqp-broker:
        condition: service_healthy
      directus:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8081/api/v1/athena/health']
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  db_data:
```

---

### 💡 Summary

These changes ensure the project works **reliably across Linux, macOS, and Docker Desktop**, removing cross-platform issues and startup race conditions.

Let me know if you'd like a pull request with this fix — happy to contribute directly. ✅
