### ISSUE TITLE
Source Dockerfile for citrineos/postgis

### ISSUE THREAD

**Issue by emerout** [citrineos/citrineos#33]
Hello CitrineOS team,

Could you please share the source Dockerfile for `citrineos/postgis:v1.1.0` image, referenced in Server/docker-compose.yml

```
services:
  # ...
  ocpp-db:
    image: citrineos/postgis:v1.1.0
```

I can't find it in the citrineos repos
