### ISSUE TITLE
Everest Not running on Mac silicon **no matching manifest for linux/arm64/v8 in the manifest list entries**

### ISSUE THREAD

**Issue by hpxix** [citrineos/citrineos#48]
**Which repository?**
Is it:

- citrineos-core/server/everest

**Describe the bug**
Description: Running the EVerest charger simulator on Mac Silicon (M1/M2) presents compatibility issues due to differences in architecture, as Docker defaults to pulling AMD64 images that are incompatible with ARM64 processors. This causes errors when attempting to start the containers in the /Server/everest directory using the docker-compose.yml setup.

**ERROR**
no matching manifest for linux/arm64/v8 in the manifest list entries

**Proposed Solution:**
To ensure compatibility and allow EVerest to run smoothly on Mac Silicon, we propose the following adjustments to the docker-compose.yml file:

**Platform Specification:**
Add platform: linux/amd64 under each service definition to enforce Docker’s usage of AMD64 images with ARM64 emulation on Apple Silicon.**

**Direct Environment Variables:**
For simpler configuration, define EVEREST_IMAGE_TAG and EVEREST_TARGET_URL directly in the environment section within docker-compose.yml. This avoids needing dynamic build-time arguments and simplifies setup.

**Updated docker-compose.yml Example aka FIX:**
<img width="605" alt="Screenshot 1446-04-26 at 9 38 19 PM" src="https://github.com/user-attachments/assets/6aada4e1-6278-4657-b117-515cf9c141c6">

**Dockerfile:**
<img width="1121" alt="Screenshot 1446-04-26 at 9 38 47 PM" src="https://github.com/user-attachments/assets/532aeeef-ae1a-48ff-a436-35382879934e">

**Steps to Reproduce:**
Clone the EVerest repository and navigate to /Server/everest.
Run npm run start-everest or npm run start-everest-windows to start the Docker containers.
Observe any errors related to architecture incompatibility.

**Expected Outcome:**
With the platform: linux/amd64 specification, Docker should emulate AMD64, allowing the containers to run seamlessly on Mac Silicon. Users should then be able to access the EVerest UI at [localhost|ip]:1880/ui/ and view OCPP logs at localhost:8888.

**Additional Context:**
 This fix aims to support ARM64 users by simplifying the setup and ensuring all components are appropriately configured for cross-platform compatibility.

**I'll commit a new Readme.md for EVerest for Mac Users later today have a great one!**

**Comment by hpxix** [comment]
I've included a new readme.md for EVerest in /server/EVerest/readme.md regarding running Everest with Mac arm64 settings:
https://github.com/citrineos/citrineos-core/pull/286

@thanaParis Please approve for merging, thank you💙.

**Comment by corrosive4354** [comment]
Check if the image supports ARM64:
If possible, check if there is an ARM64 version of the EVerest image. If so, using that version may be more efficient.

If it still doesn't work,
There are too many compatibility issues between docker and mac. You can use [Servbay](https://servbay.com) instead of docker to deploy the environment. Servbay is more professional on mac.

**Comment by elliot-sabitov** [comment]
@hpxix we were looking deeper into this as well, and we did see that initially on ARM64 we see the `no matching manifest for linux/arm64/v8 in the manifest list entries` error and when we add `platform=linux/amd64` then it does move past that error, but when `manager` starts up, it just immediately fails with:

```
2024-05-24 18:26:39.489204 [ERRO] manager         int main(int, char**) :: Main manager process exits because of caught exception:
Syscall pipe2() failed (Invalid argument), exiting
```

Were you able to get around this and actually have Everest running?

**Comment by elliot-sabitov** [comment]
I followed the changes that you have made in the video https://www.loom.com/share/e7fd054e4d224918a722d14eb834665b and I am seeing the above error (`Syscall pipe2() failed`). 

I am on a 2021 Macbook Pro with Apple M1 Max Chip. I tried running via `npm run start-everest` and manually running the compose command. It seems that no matter what I do, I end up seeing this error and the manager exists immediately... 

![Screenshot 2024-10-29 at 2 12 46 PM](https://github.com/user-attachments/assets/80344709-a75b-446b-8c15-04be82c9cadc)

**Comment by hpxix** [comment]
Actually, my PR didn't include all changes but if you go through my version of the fix for the issue above it'll work,

****Main changes that are done in docker-compose.yml;****

add platform tag = linux/amd64 to all services,
add environment variables in manager service that are 
`-EVEREST_TARGET_URL=ws://EVEREST_TARGET_URL=ws://host.docker.internal:8081/cp001`
`- EVEREST_IMAGE_TAG=0.0.16`

_**remove in manager service;**_
`    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4G'`
          
****Instead added network tag to use  bridge for all services****
add context tag above dockerfile: Dockerfile in 

****For Dockerfile simply just change platform to linux/amd64****  

@elliot-sabitov let me know how this goes for you also use docker compose to run everest and not node or at least that what works for me 

@thanaParis Also I'll make sure to include the new updates on my PR 

Cheers💙

**Comment by hpxix** [comment]
@thanaParis I've added a new PR with the latest changes on the readme.md for server/everest:
https://github.com/citrineos/citrineos-core/pull/286/commits/eceaaec97464cfb43e85b2bab7108dd3ea2771e2

**Comment by elliot-sabitov** [comment]
@hpxix I tried with the following 2 files just now (see below) that I got from your commit here https://github.com/citrineos/citrineos-core/commit/eceaaec97464cfb43e85b2bab7108dd3ea2771e2, but unfortunately I am still seeing this error `Syscall pipe2() failed (Invalid argument), exiting` - I am wondering what else may be different on my machine vs yours and I am very eager to get this working on our M1 machines and hope that we can get this resolved! Thank you so much for your help!
```
// docker-compose.xml
version: '3.8'
services:
  mqtt-server:
    image: ghcr.io/everest/everest-demo/mqtt-server:0.0.16
    platform: linux/amd64
    networks:
      - everest-net
    logging:
      driver: none
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8888:8888
    networks:
      - everest-net
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - EVEREST_TARGET_URL=ws://host.docker.internal:8081/cp001
      - EVEREST_IMAGE_TAG=0.0.16
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  nodered:
    image: ghcr.io/everest/everest-demo/nodered:0.0.16
    platform: linux/amd64
    networks:
      - everest-net
    depends_on:
      - mqtt-server
    ports:
      - 1880:1880
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-two-evse-flow.json
networks:
  everest-net:
    driver: bridge
```

and

```
// Dockerfile
ARG EVEREST_IMAGE_TAG=0.0.16
FROM --platform=linux/amd64 ghcr.io/everest/everest-demo/manager:${EVEREST_IMAGE_TAG}
ARG EVEREST_TARGET_URL=ws://host.docker.internal:8081/cp001
ENV EVEREST_TARGET_URL $EVEREST_TARGET_URL
WORKDIR /workspace
RUN ["/entrypoint.sh"]
RUN apk update && apk add sqlite
RUN sqlite3 /ext/source/build/dist/share/everest/modules/OCPP201/device_model_storage.db \
        "UPDATE VARIABLE_ATTRIBUTE \
        SET value = '[{\"configurationSlot\": 1, \"connectionData\": {\"messageTimeout\": 30, \"ocppCsmsUrl\": \"$EVEREST_TARGET_URL\", \"ocppInterface\": \"Wired0\", \"ocppTransport\": \"JSON\", \"ocppVersion\": \"OCPP20\", \"securityProfile\": 1}},{\"configurationSlot\": 2, \"connectionData\": {\"messageTimeout\": 30, \"ocppCsmsUrl\": \"$EVEREST_TARGET_URL\", \"ocppInterface\": \"Wired0\", \"ocppTransport\": \"JSON\", \"ocppVersion\": \"OCPP20\", \"securityProfile\": 1}}]' \
        WHERE \
        variable_Id IN ( \
        SELECT id FROM VARIABLE \
        WHERE name = 'NetworkConnectionProfiles' \
        );"
RUN rm /ext/source/build/dist/etc/everest/certs/ca/v2g/*.*
RUN npm i -g http-server
EXPOSE 8888
COPY ./start.sh /tmp/start.sh
RUN chmod +x /tmp/start.sh
CMD ["sh", "-c", "/tmp/start.sh"]
```
